version: "3.9"

services:
  postgres-credits:
    image: postgres:15
    container_name: banque-credits-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: banque_credits  # ← PostgreSQL va créer cette base au démarrage

    ports:
      - "${POSTGRES_PORT}:5432"  # Port hôte 5434 mappé au port 5432 du container
    volumes:
      - postgres-credits-data:/var/lib/postgresql/data
    networks:
      - banque-network

volumes:
  postgres-credits-data:

networks:
  banque-network:
    driver: bridge
