version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: banque-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - banque-network

volumes:
  postgres-data:

networks:
  banque-network:
    driver: bridge
