# Nom de l'application
spring.application.name=service-notification

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5436/banque_notification
spring.datasource.username=admin
spring.datasource.password=admin
server.port=8085

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JavaMail / SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eelouahinajat@gmail.com
spring.mail.password=czaszlbybbpamrde
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=eelouahinajat@gmail.com

#rabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nom de la queue pour notifications
notification.queue=notification-queue
